import type { Project, Layer, AnimatableProp, Transform, Color, FillValue } from '../../types';
import { interpolateTransform, interpolateNumber, interpolateColor, interpolateFill } from '../interpolator';

function colorToCss(c: Color): string {
  return `rgba(${c.r}, ${c.g}, ${c.b}, ${c.a})`;
}

function fillToCss(fill: FillValue): string {
  if (fill.type === 'none') return 'transparent';
  if (fill.type === 'solid') return colorToCss(fill.color);
  return 'transparent';
}

function layerToCssKeyframes(layer: Layer, fps: number, totalFrames: number): string {
  const steps = 20;
  const lines: string[] = [];

  for (let s = 0; s <= steps; s++) {
    const frame = (s / steps) * totalFrames;
    const pct = (s / steps) * 100;
    const t = interpolateTransform(layer.properties.transform, frame);
    const opacity = interpolateNumber(layer.properties.opacity, frame, 100) / 100;
    const fill = interpolateFill(layer.properties.fill, frame);

    lines.push(
      `  ${pct.toFixed(1)}% {
    transform: translate(${t.x}px, ${t.y}px) rotate(${t.rotation}deg) scale(${t.scaleX}, ${t.scaleY});
    opacity: ${opacity.toFixed(3)};
    fill: ${fillToCss(fill)};
  }`,
    );
  }

  return `@keyframes ${layer.id} {\n${lines.join('\n')}\n}`;
}

export function exportCssKeyframes(project: Project): string {
  const blocks: string[] = [`/* Generated by Motif — ${project.name} */`];
  for (const layer of project.layers) {
    if (!layer.visible) continue;
    blocks.push(layerToCssKeyframes(layer, project.fps, project.totalFrames));
    blocks.push(
      `.${layer.id} { animation: ${layer.id} ${(project.totalFrames / project.fps).toFixed(2)}s linear infinite; }`,
    );
  }
  return blocks.join('\n\n');
}
